import type { StaticAssets } from "../types";

export const staticAssets: StaticAssets = {
  images: [
    "/images/about.webp",
    "/images/aboutlogo.webp",
    "/images/adam.webp",
    "/images/amLogo.webp",
    "/images/aws.webp",
    "/images/blog.webp",
    "/images/bluishavatar.webp",
    "/images/contact.webp",
    "/images/flask.webp",
    "/images/fullLogo.webp",
    "/images/greenavatar.webp",
    "/images/musiwrite.webp",
    "/images/ollama.webp",
    "/images/orangeavatar.webp",
    "/images/portfolio.webp",
    "/images/projects.webp",
    "/images/pvault.webp",
    "/images/python.webp",
    "/images/react.svg",
    "/images/redavatar.webp",
    "/images/skills.webp",
    "/images/tailwind.webp",
    "/images/ThreeJS.webp",
  ],
  videos: [
    "/videos/black_ios.mp4",
    "/videos/noted_ios.mp4",
    "/videos/static_ios.mp4",
    "/videos/white_ios.mp4",
  ],
  fonts: [
    "/fonts/Inter_Bold.json",
    "/fonts/net_sans_bold.otf",
    "/fonts/net_sans_light.otf",
    "/fonts/net_sans_med.otf",
  ],
  hdris: ["/hdris/fireplace.exr", "/fireplace.hdr"],
};
